app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime



@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))



class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    reviews = db.relationship('Review',backref = 'user',lazy = "dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)


    def __repr__(self):
        return f'User {self.username}'


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")

    def __repr__(self):
        return f'User {self.name}'


class Review(db.Model):

    __tablename__ = 'reviews'

    id = db.Column(db.Integer,primary_key = True)
    movie_id = db.Column(db.Integer)
    movie_title = db.Column(db.String)
    image_path = db.Column(db.String)
    movie_review = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

    def save_review(self):
        db.session.add(self)
        db.session.commit()


    @classmethod
    def get_reviews(cls,id):

        reviews = Review.query.filter_by(movie_id=id).all()
        return reviews



class Movie:
    '''
    Movie class to define Movie Objects
    '''

    def __init__(self,id,title,overview,poster,vote_average,vote_count):
        self.id =id
        self.title = title
        self.overview = overview
        self.poster = "https://image.tmdb.org/t/p/w500/" + poster
        self.vote_average = vote_average
        self.vote_count = vote_count

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')
    
class ReviewForm(FlaskForm):

    title = StringField('Review title',validators=[Required()])
    review = TextAreaField('Movie review')
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_mail import Mail
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_simplemde import SimpleMDE


db = SQLAlchemy()
mail = Mail()
bootstrap = Bootstrap()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

photos = UploadSet('photos',IMAGES)

simple = SimpleMDE()

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    # configure UploadSet
    configure_uploads(app,photos)


    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    

    # setting config
    from .requests import configure_request
    configure_request(app)


    # Will add the views and forms

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..requests import get_movies,get_movie,search_movie
from .forms import ReviewForm,UpdateProfile
from ..models import Review
from flask_login import login_required, current_user
from ..models import Review, User
from .. import db,photos
import markdown2


# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''

    # Getting popular movie
    popular_movies = get_movies('popular')
    upcoming_movie = get_movies('upcoming')
    now_showing_movie = get_movies('now_playing')

    title = 'Home - Welcome to The best Movie Review Website Online'

    search_movie = request.args.get('movie_query')

    if search_movie:
        return redirect(url_for('search',movie_name=search_movie))
    else:
        return render_template('index.html', title = title, popular = popular_movies, upcoming = upcoming_movie, now_showing = now_showing_movie )

@main.route('/movie/<int:id>')
def movie(id):

    '''
    View movie page function that returns the movie details page and its data
    '''
    movie = get_movie(id)
    title = f'{movie.title}'
    reviews = Review.get_reviews(movie.id)

    return render_template('movie.html',title = title,movie = movie,reviews = reviews)

@main.route('/search/<movie_name>')
def search(movie_name):
    '''
    View function to display the search results
    '''
    movie_name_list = movie_name.split(" ")
    movie_name_format = "+".join(movie_name_list)
    searched_movies = search_movie(movie_name_format)
    title = f'search results for {movie_name}'
    return render_template('search.html',movies = searched_movies)

@main.route('/reviews/<int:id>')
def movie_reviews(id):
    movie = get_movie(id)

    reviews = Review.get_reviews(id)
    title = f'All reviews for {movie.title}'
    
    return render_template('movie_reviews.html',title = title,reviews=reviews)


@main.route('/movie/review/new/<int:id>', methods = ['GET','POST'])
@login_required
def new_review(id):
    form = ReviewForm()
    movie = get_movie(id)
    if form.validate_on_submit():
        title = form.title.data
        review = form.review.data
        # Updated review instance
        new_review = Review(movie_id=movie.id,movie_title=title,image_path=movie.poster,movie_review=review,user=current_user)

        # save review method
        new_review.save_review()
        return redirect(url_for('.movie',id = movie.id ))

    title = f'{movie.title} review'
    return render_template('new_review.html',title = title, review_form=form, movie=movie)

@main.route('/review/<int:id>')
def single_review(id):
    review=Review.query.get(id)
    format_review = markdown2.markdown(review.movie_review,extras=["code-friendly", "fenced-code-blocks"])

    return render_template('review.html',review = review,format_review=format_review)





@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    review = Review.query.filter_by(user_id = user.id).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user,review = review)




@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)




@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

<!-- Styles block -->

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

<!-- Content block -->
{% block content %}

<div class="container">
    <form>
        <input type="text" name="movie_query" placeholder="Search for a Movie" class="form-control">
        <input type="submit"  value="Submit" class="btn btn-default">
    </form>

</div>

<!-- Popular movie -->
<h3> Popular Movies</h3>
<ul>
    {{ macro.displayMovieList(popular)}}
</ul>
<!-- Upcoming movie  -->
<h3> Upcoming Movies </h3>
<ul>
    {{ macro.displayMovieList(upcoming)}}
</ul>
<!-- Now showing movie -->
<h3>Now Showing</h3>
<ul>
    {{ macro.displayMovieList(now_showing)}}
</ul>


{% endblock%}

app/templates/macros.html
{% macro displayMovieList(movie_list) %}

{% for movie in movie_list %}
<div class="col-xs-12 col-sm-4 col-md-2 col-lg-2 movie-card">
    <img src="{{ movie.poster }}" alt="{{ movie.title }} poster" class="img-responsive">
    <li class="text-center">
        <a href="/movie/{{movie.id}}">
            {{ movie.title|truncate(10)}}</a>
    </li>
</div>

{% endfor %}

{% endmacro %}

<!-- Displaying reviews macro -->
{% macro displayReviews(review_list) %}
{% for review in review_list %}
<div class="row">

    <div class="col-xs-2 col-sm-2 col-md-4 col-lg-4">
        <h4>Author</h4>
        <p>{{review.user.username}}</p>
    </div>
    <div class="col-xs-10 col-sm-10 col-md-8 col-lg-8">
        <h2> <a href="{{url_for('main.single_review',id=review.id)}}">{{review.movie_title}}</a> </h2>
    </div>
</div>
{% endfor %}
{% endmacro %}

app/templates/movie.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

<!-- Content block -->
{% block content %}
<div class="container">

    <!-- Poster background -->
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 posterPath"
            style="background: url({{movie.poster}}) no-repeat center center">
        </div>

        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 movie-details">

            <h3>{{ movie.title }}</h3>

            <p class="overview"> {{ movie.overview }}</p>

            <p class="ratings"> <b> {{ movie.vote_average }}</b> - <i>{{ movie.vote_count}} votes </i> </p>
            <a class="ratings" href="/movie/review/new/{{movie.id}}"> Write a new review</a>

        </div>

    </div>
    <div class="row">

        <h1>Reviews</h1>
        <hr>

        {% if reviews %}
        {{macro.displayReviews(reviews)}}

        {% else%}
        <h3 class="text-center">This movie has no reviews </h3>

        <a class="btn btn-success btn-lg text-center" href="/movie/review/new/{{movie.id}}"> Write a new review</a>
        {% endif %}

    </div>


</div>
{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Watchlist </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>
        </div>

    </div>
</div>

app/templates/new_review.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">

    <div class="col-md-8">

        <img src="{{movie.poster}}" alt="{{movie.title}}" class="img-responsive">
    </div>

    <div class="col-md-4">

        {{ wtf.quick_form(review_form) }}
        {{simplemde.load}}

    </div>

</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <div class="row">
                <div class="col-sm-4">
                    <img src="{{review.image_path}}" class="img-responsive">
                </div>

                <div class="col-sm-8">
                    {{review.movie_review|safe}}
                </div>
            </div>


            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}

            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}

            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
            {% endif %}

        </div>

        <!--Display profile photo-->
        <div class="col-md-4">
            {% if user.profile_pic_path %}

            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

            {%else%}
            <p>No profile picture</p>

            {% endif %}

            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post"
                enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/review.html
{% extends 'base.html'%}

{% block content%}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-4">
            <img src="{{review.image_path}}" class="img-responsive">
        </div>

        <div class="col-sm-8">
            {{format_review|safe}}
        </div>
    </div>
</div>
{%endblock%}

app/templates/search.html
{% import 'macros.html' as macro%}

{% block content %}
    <div class="container">

        <div class="row">

            <h3> Found {{ movies| count }} matches </h3>
            <hr>
            <ul>
                {{ macro.displayMovieList(movies)}}
            </ul>

        </div>

    </div>
{% endblock %}